### ISSUE TITLE
Send Bram the current state of the files to vim-perl

### ISSUE THREAD

**Issue by petdance** [vim-perl/vim-perl#249] opened 2017-06-12 14:55 UTC
We haven't sent anything to Bram since July 2013.

**Comment by jamessan** [comment] 2017-09-11 03:25
Any update on this?

**Comment by petdance** [comment] 2017-09-11 14:23
No update. It would require a fair amount of work to document what's been changed, and with 8.0 already out, it hasn't felt like a priority.

**Comment by petdance** [comment] 2017-09-11 14:25
@jamessan Does this affect you in some way?

**Comment by jamessan** [comment] 2017-09-11 14:30
> It would require a fair amount of work to document what's been changed

Well, that's not going to change as time goes on and there's no need to provide documentation to Bram about what has been changed.  He trusts the maintainers to send him appropriate updates.

> with 8.0 already out, it hasn't felt like a priority.

Vim releases don't really matter in the grand scheme of things.  No one packages Vim based on the major releases.

> Does this affect you in some way?

Yes.  I maintain the Debian Vim packages and every one of my users is running into bugs that have been fixed in the past 4+ years but haven't been released to the broader Vim community.  Whenever a bug comes in about the Perl files, that has not only wasted the user's time but also my time in triaging what the issue is and whether I need to report it here.

**Comment by petdance** [comment] 2017-09-11 14:32
> No one packages Vim based on the major releases.

> Yes. I maintain the Debian Vim packages 

I hadn't even considered that.  That puts things in a whole new light.

**Comment by hoelzro** [comment] 2017-09-11 17:46
For reference, this is what I did last time: https://groups.google.com/forum/#!searchin/vim_dev/rob$20hoelz/vim_dev/BckxSMJb_sc/wpHPV5zcRToJ

Keep in mind that we'll probably need to do this for Perl 6 as well.

**Comment by petdance** [comment] 2017-09-11 17:53
A couple of thoughts.

1) We'll be doing a release even though we aren't uploading a tarball to some repo.  Maybe we'll call it "bram-2017-09-12" or something similar.  And tag it as such once it's put on master.

2) This release needs release notes, so that people can know what's what on master, separate from dev.

3) perl6 and perl are now separate projects, so pushing a release to bram of perl5 does not necessarily mean perl6 will get released, and vice versa.

**Comment by hoelzro** [comment] 2017-09-12 16:14
Ok, apparently that was a patch to update the syntax.txt documentation to reflect new options in the Perl syntax file, rather than updates to the syntax file itself.  Which means...

1. I need to find when I sent this patch to Bram

2. We likely need to make a PR to update the syntax file docs if the changelog has any new user options or something.

There are also changes made to syntax/perl.vim in upstream Vim that haven't made their way down to vim-perl yet - these will need to be incorporated.

**Comment by hoelzro** [comment] 2017-09-12 16:41
Ok - we submitted 6b95306 to Bram privately, which was integrated into Vim as github.com/vim/vim/commit/9d98fe9ca

**Comment by hoelzro** [comment] 2017-09-12 16:42
(Which debuted in Vim 7.4)

**Comment by hoelzro** [comment] 2017-09-13 03:34
So I started looking at the diffs between our tree and upstream - I started this in a branch called https://github.com/vim-perl/vim-perl/tree/release-prep.

While looking at the changes, I noticed that `syntax/tap.vim` is present in our tree but not upstream - should we submit this upstream or leave it out?

**Comment by petdance** [comment] 2017-09-13 03:37
I think we should send it upstream.

It makes for vim to handle TAP, although I don't necessarily think we need to always be the one to maintain it.

**Comment by hoelzro** [comment] 2017-09-13 03:39
@petdance Ok, I'll include it then!

**Comment by hoelzro** [comment] 2017-09-13 03:41
Hmm...should we send our PR upstream from a `vim-perl` vim fork, or should I send it from my private fork?

**Comment by petdance** [comment] 2017-09-13 03:46
Can't think about it right now.  Let's discuss tomorrow.  Ping me in Slack.

**Comment by hoelzro** [comment] 2017-09-13 03:57
👍 Either way, I have the branch ready to go in my fork: https://github.com/hoelzro/vim/commit/ce2712a090fb33c7044d5419de1e9dfe8e6d72c6

**Comment by hoelzro** [comment] 2017-09-15 01:58
@jamessan I've filed a PR against https://github.com/vim/vim: https://github.com/vim/vim/pull/2083

@petdance Bram has a question about tap.vim - how *are* TAP files recognized?

**Comment by jamessan** [comment] 2017-09-15 02:00
Thanks @hoelzro. :+1:

**Comment by hoelzro** [comment] 2017-11-01 16:25
So, the PR is still in a pending state, but it looks like the changes made it into Vim 8.0.1129!

**Comment by hoelzro** [comment] 2017-11-01 16:25
@jamessan ^

**Comment by petdance** [comment] 2017-11-01 16:41
> Bram has a question about tap.vim - how are TAP files recognized?

I don't think there is a way.  The obvious would be *.tap, but I don't even know if that's appropriate globally.

**Comment by petdance** [comment] 2017-11-01 16:42
I guess we could look for `/^(not )?ok\s*\d+/` on line 1 or line 2 as a heuristic.

**Comment by cdluminate** [comment] 2019-05-06 10:59
Hi there. Any updates? Vim's perl6 syntax file has some performance issue: https://github.com/vim/vim/issues/4339

**Comment by petdance** [comment] 2019-05-06 14:16
The Perl6 side has its own ticket for this, too: https://github.com/vim-perl/vim-perl6/issues/12

**Closed** 2022-06-30 03:45 UTC
